CREATE TABLE USUARIO(
	CODIGO        INTEGER     NOT NULL PRIMARY KEY,
	NOME  	      VARCHAR(70) NOT NULL,
	ADMINISTRADOR BOOLEAN     NOT NULL,
	CPF	      VARCHAR(11) NOT NULL,
	SENHA         VARCHAR(100) NOT NULL,
	CELULAR	      VARCHAR(11)
);

CREATE TABLE AUTOR(
	CODIGO INTEGER 	   NOT NULL PRIMARY KEY,
	NOME   VARCHAR(70) NOT NULL
);

CREATE TABLE EDITORA(
	CODIGO INTEGER     NOT NULL PRIMARY KEY,
	NOME   VARCHAR(70) NOT NULL
);

CREATE TABLE LIVRO(
	CODIGO         INTEGER NOT NULL PRIMARY KEY,
	TITULO 	       INTEGER NOT NULL,
	EDITORA_CODIGO INTEGER,
	AUTOR_CODIGO   INTEGER,
	CONSTRAINT FK_EDITORA_LIVRO FOREIGN KEY (EDITORA_CODIGO) REFERENCES EDITORA(CODIGO),
	CONSTRAINT FK_AUTOR_LIVRO FOREIGN KEY (AUTOR_CODIGO) REFERENCES AUTOR(CODIGO)
);
	
CREATE TABLE EMPRESTIMO(
	CODIGO         INTEGER NOT NULL PRIMARY KEY,
	LIVRO_CODIGO   INTEGER NOT NULL,
	USUARIO_CODIGO INTEGER NOT NULL,
	DATARETIRADA   DATE    NOT NULL,
	DATAVENCIMENTO DATE    NOT NULL,
	DATADEVOLUCAO  DATE,
	MULTA          NUMERIC(15,2),
	CONSTRAINT FK_LIVRO_EMPRESTIMO   FOREIGN KEY (LIVRO_CODIGO)   REFERENCES LIVRO(CODIGO),
	CONSTRAINT FK_USUARIO_EMPRESTIMO FOREIGN KEY (USUARIO_CODIGO) REFERENCES USUARIO(CODIGO)
);