CREATE TABLE TABELA (
	NOME VARCHAR(30) NOT NULL PRIMARY KEY
);

CREATE TABLE CAMPO (
	TABELA_NOME VARCHAR(50) NOT NULL,
	NOME 	    VARCHAR(50) NOT NULL,
	DESCRICAO   VARCHAR (200) NOT NULL,
	TIPO        VARCHAR(50) NOT NULL,
	CAMPOPK     BOOLEAN NOT NULL  DEFAULT FALSE,
	CAMPOFK     VARCHAR(50),
	TABELAFK    VARCHAR(50),
	CONSTRAINT PK_CAMPO PRIMARY KEY(TABELA_NOME, NOME),
	CONSTRAINT FK_TABELA_CAMPO FOREIGN KEY(TABELA_NOME)  	  REFERENCES TABELA(NOME),
	CONSTRAINT FK_CAMPO_CAMPO  FOREIGN KEY(TABELAFK, CAMPOFK) REFERENCES CAMPO(TABELA_NOME, NOME)
);

CREATE TABLE USUARIO(
	CODIGO        INTEGER     NOT NULL PRIMARY KEY,
	NOME  	      VARCHAR(70) NOT NULL,
	SENHA         VARCHAR(15) NOT NULL,
	ADMINISTRADOR BOOLEAN     NOT NULL,
	CPF	      VARCHAR(11) NOT NULL,
	RG	      VARCHAR(20),
	CELULAR	      VARCHAR(11) NOT NULL,
	TELEFONE      VARCHAR(11)
);

CREATE TABLE AUTOR(
	CODIGO INTEGER 	   NOT NULL PRIMARY KEY,
	NOME   VARCHAR(70) NOT NULL
);

CREATE TABLE EDITORA(
	CODIGO INTEGER     NOT NULL PRIMARY KEY,
	NOME   VARCHAR(70) NOT NULL
);

CREATE TABLE LIVRO(
	CODIGO         INTEGER NOT NULL PRIMARY KEY,
	TITULO 	       INTEGER NOT NULL,
	ISBN 	       VARCHAR(20) NOT NULL,
	EDITORA_CODIGO INTEGER,
	DESCRICAO      TEXT,
	ANO            SMALLINT,
	CONSTRAINT FK_EDITORA_LIVRO FOREIGN KEY (EDITORA_CODIGO) REFERENCES EDITORA(CODIGO)
);

CREATE TABLE AUTORLIVRO(
	CODIGO INTEGER NOT NULL PRIMARY KEY,
	AUTOR_CODIGO INTEGER NOT NULL,
	LIVRO_CODIGO INTEGER NOT NULL,
	CONSTRAINT FK_AUTOR_AUTORLIVRO FOREIGN KEY (AUTOR_CODIGO) REFERENCES AUTOR(CODIGO),
	CONSTRAINT FK_LIVRO_AUTORLIVRO FOREIGN KEY (LIVRO_CODIGO) REFERENCES LIVRO(CODIGO)
);

CREATE TABLE EMPRESTIMO(
	CODIGO         INTEGER NOT NULL PRIMARY KEY,
	LIVRO_CODIGO   INTEGER NOT NULL,
	USUARIO_CODIGO INTEGER NOT NULL,
	DATARETIRADA   DATE    NOT NULL,
	DATAVENCIMENTO DATE    NOT NULL,
	DATADEVOLUCAO  DATE,
	MULTA          NUMERIC(15,2),
	CONSTRAINT FK_LIVRO_EMPRESTIMO   FOREIGN KEY (LIVRO_CODIGO)   REFERENCES LIVRO(CODIGO),
	CONSTRAINT FK_USUARIO_EMPRESTIMO FOREIGN KEY (USUARIO_CODIGO) REFERENCES USUARIO(CODIGO)
);